FROM python:3.12
WORKDIR /app
RUN pip install poetry
RUN poetry config virtualenvs.create false
COPY pyproject.toml poetry.lock /app/
RUN poetry install --only main --no-root
COPY src /app/src
COPY .env .env.dev .env.prod* /app/

CMD ["poetry", "run", "python", "-m", "src.jobs.cleanup"]
