apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-creator
rules:
  - apiGroups: [""] # core
    resources: ["secrets"]
    verbs: ["create", "get", "patch"]
  - apiGroups: ["example.com"]
    resources: ["surveys", "participations"]
    verbs: ["get", "create", "list", "delete", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-creator-binding
subjects:
  - kind: ServiceAccount
    name: builder-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: job-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simulation-orchestrator
  namespace: default
---
# TODO: check rules!
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simulation-orchestrator
rules:
  - apiGroups: [""]
    resources:
      [
        "namespaces",
        "pods",
        "services",
        "persistentvolumeclaims",
        "events",
        "secrets",
      ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["example.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simulation-orchestrator
subjects:
  - kind: ServiceAccount
    name: simulation-orchestrator
    namespace: default
roleRef:
  kind: ClusterRole
  name: simulation-orchestrator
  apiGroup: rbac.authorization.k8s.io