apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: participations.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["userId", "surveyName"]
              properties:
                userId:
                  type: string
                surveyName:
                  type: string
                overrides:
                  type: object
                  properties:
                    resourceLimits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    rosbagTopics:
                      type: array
                      items:
                        type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                phase:
                  type: string
                  enum: ["Pending", "Running", "Completed", "Failed"]
                rosbagFile:
                  type: string
                startTime:
                  type: string
                  format: date-time
                completionTime:
                  type: string
                  format: date-time
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: User
          type: string
          jsonPath: .spec.userId
  scope: Cluster
  names:
    plural: participations
    singular: participation
    kind: Participation
    shortNames:
      - paci
